from __future__ import annotations

from dataclasses import asdict, dataclass
from enum import StrEnum
from hashlib import sha256
from types import MappingProxyType
from typing import Any, Iterable
import json
import re


DEFECT_REGISTRY_VERSION = "defect_registry.v1"
_SAFE_CODE = re.compile(r"^[A-Z0-9][A-Z0-9_:-]{0,119}$")


class DefectDomain(StrEnum):
    ACTIVITY = "activity"
    ASSET = "asset"
    CAPTION = "caption"
    CATALOG = "catalog"
    EVIDENCE = "evidence"
    INFRASTRUCTURE = "infrastructure"
    OUTCOME = "outcome"
    PLANNING = "planning"
    PROVIDER = "provider"
    RENDER = "render"
    SECURITY = "security"
    SOURCE = "source"
    UNKNOWN = "unknown"
    WORKSPACE = "workspace"


class DefectSeverity(StrEnum):
    ADVISORY = "advisory"
    LIMITATION = "limitation"
    RETRYABLE = "retryable"
    TECHNICAL_BLOCKER = "technical_blocker"
    TERMINAL = "terminal"


class DefectVisibility(StrEnum):
    AUDIT = "audit"
    INTERNAL = "internal"
    PUBLIC = "public"


class RepairStrategy(StrEnum):
    ADVISORY = "advisory"
    CONDITIONAL_LLM_OR_FALLBACK = "conditional_llm_or_fallback"
    DETERMINISTIC_FALLBACK = "deterministic_fallback"
    LLM_PLAN_REPAIR = "llm_plan_repair"
    LLM_VISUAL_REPAIR = "llm_visual_repair"
    PROVIDER_RETRY = "provider_retry"
    RENDERER_RETRY_OR_FAIL = "renderer_retry_or_fail"
    TERMINAL = "terminal"


class RepairPhase(StrEnum):
    COMPILE = "compile"
    NONE = "none"
    POST_RENDER = "post_render"
    PRE_RENDER = "pre_render"
    TRANSPORT = "transport"
    VISUAL_UNDERSTANDING = "visual_understanding"


class RetryAction(StrEnum):
    NONE = "none"
    OPERATOR_REVIEW = "operator_review"
    RETRY_DEFECTS = "retry_defects"
    RETRY_SAME_VERSION = "retry_same_version"


class PromotionClass(StrEnum):
    ADVISORY = "advisory"
    CREATIVE_LIMITATION = "creative_limitation"
    TECHNICAL_BLOCKER = "technical_blocker"
    TERMINAL = "terminal"


@dataclass(frozen=True)
class DefectDefinition:
    code: str
    domain: DefectDomain
    default_severity: DefectSeverity
    visibility: DefectVisibility
    repair_strategy: RepairStrategy
    repair_phase: RepairPhase
    evidence_requirements: tuple[str, ...]
    safe_fallback_code: str | None
    retryable: bool
    retry_action: RetryAction
    promotion_class: PromotionClass
    title_en: str
    description_en: str
    title_es: str
    description_es: str
    legacy_aliases: tuple[str, ...] = ()
    detector: str | None = None
    threshold: str | None = None
    trigger_eligible: bool = False


def _code_set(value: str) -> frozenset[str]:
    return frozenset(item for item in value.split() if item)


_REGISTERED_CODES = _code_set(
    """
    ACTIVE_PICTURE_TOO_SMALL ACTIVE_PICTURE_UNAVAILABLE ACTIVITY_STREAM_UNAVAILABLE
    AGENTIC_EDITING_DISABLED AGENTIC_EDITING_CONFIG_INVALID AGENTIC_PREFLIGHT_FAILED
    AGENTIC_RENDER_ASSET_MISSING AGENTIC_RENDER_CLIP_MISMATCH AGENTIC_VIDEO_RENDER_FAILED
    ASSET_BUDGET_EXCEEDED ASSET_CONFIG_INVALID ASSET_IDS_NOT_UNIQUE ASSET_LIMIT_EXCEEDED
    ASSET_LIMIT_INVALID ASSET_OVERLAY_DUPLICATED ASSET_OVERLAY_IDS_MISMATCH
    ASSET_OVERLAY_NOT_VISIBLE ASSET_OVERLAY_OPACITY_TOO_LOW ASSET_OVERLAY_TIMING_MISMATCH
    ASSET_PENDING ASSET_POLICY_BLOCKED ASSET_POLICY_INVALID ASSET_PROVIDER_UNAVAILABLE
    ASSET_TIMELINE_OUTSIDE_CLIP ASSET_UNRESOLVED ASSET_VISIBILITY_ANALYSIS_UNAVAILABLE
    ASSET_VISIBILITY_ASSET_INVALID ASSET_VISIBILITY_ASSET_UNRESOLVED
    ASSET_VISIBILITY_GEOMETRY_INVALID ASSET_VISIBILITY_LIMIT_REACHED
    ASSET_VISIBILITY_TIMING_INVALID ATTENTION_GAP AUDIO_CODEC_UNEXPECTED
    AUDIO_EXTRACTION_FAILED AUDIO_MISSING AUTH_UNAVAILABLE BASELINE_FALLBACK_CONFIG_INVALID
    BLACK_FRAMES_DETECTED CAPABILITY_UNAVAILABLE CAPABILITY_UNDECLARED
    CAPTION_CONFIG_INVALID CAPTION_CUE_LIMIT_EXCEEDED CAPTION_DIMENSIONS_INVALID
    CAPTION_FFMPEG_UNAVAILABLE CAPTION_FOOTPRINT_BLOCKED CAPTION_FOOTPRINT_TIMEOUT
    CAPTION_FOOTPRINT_UNAVAILABLE CAPTION_FOOTPRINT_UNMEASURABLE CAPTION_HEIGHT_EXCEEDED
    CAPTION_LINE_LIMIT_EXCEEDED CAPTION_OUTSIDE_FOOTER_SAFE_ZONE
    CAPTION_OUTSIDE_FRAME_SAFE_ZONE CAPTION_PATH_INVALID CAPTION_READING_SPEED_EXCEEDED
    CAPTION_SAFE_ZONE_FALLBACK CAPTION_WIDTH_EXCEEDED CATALOG_CONFIG_HASH_MISMATCH
    CATALOG_CONFIG_INVALID CATALOG_FALLBACK_INVALID CATALOG_FFMPEG_FILTER_MISSING
    CATALOG_FFMPEG_UNAVAILABLE CATALOG_FILE_CONFIG_INVALID CATALOG_FILE_HASH_MISMATCH
    CATALOG_FILE_MISSING CATALOG_FILE_PATH_INVALID CATALOG_FILE_TYPE_INVALID
    CATALOG_FONT_FAMILY_MISMATCH CATALOG_FONT_GLYPHS_MISSING CATALOG_FONT_INVALID
    CATALOG_FONT_PROBE_UNAVAILABLE CATALOG_HASH_INVALID CATALOG_ID_DUPLICATE
    CATALOG_ID_INVALID CATALOG_KIND_INVALID CATALOG_LABEL_INVALID CATALOG_LICENSE_BLOCKED
    CATALOG_LICENSE_HASH_MISMATCH CATALOG_LICENSE_INVALID CATALOG_LICENSE_MISSING
    CATALOG_LICENSE_PATH_INVALID CATALOG_MANIFEST_INVALID CATALOG_MANIFEST_UNAVAILABLE
    CATALOG_REFERENCE_MISSING CATALOG_REQUIRED_ENTRY_MISSING CATALOG_REVIEW_INVALID
    CATALOG_RIGHTS_UNVERIFIED CATALOG_SOURCE_INVALID CATALOG_VERSION_INVALID
    CHECKPOINT_DATABASE_UNAVAILABLE CHECKPOINT_FINGERPRINT_INVALID CHECKPOINT_HASH_MISMATCH
    CHECKPOINT_JOB_UNAVAILABLE CHECKPOINT_PATH_INVALID CHECKPOINT_PAYLOAD_INVALID
    CHECKPOINT_SIZE_MISMATCH CHECKPOINT_SOURCE_UNAVAILABLE CHECKPOINT_STAGE_INVALID
    CHECKPOINT_TOO_LARGE CHECKPOINT_WRITE_FAILED CLIP_TIMELINE_INCOMPLETE
    COMPOSITION_CROP_TARGET_TOO_WIDE COMPOSITION_LAYOUT_UNSUPPORTED
    CREATIVE_CONFORMANCE_UNAVAILABLE CREATIVE_INTENT_CAPABILITY_UNAVAILABLE
    CREATIVE_INTENT_UNMET CREATIVE_QA_UNAVAILABLE CROP_TARGET_MISSING
    CROP_VISUAL_GAP_TOO_LARGE CROP_VISUAL_OBSERVATION_MISSING
    CROP_VISUAL_OBSERVATIONS_INSUFFICIENT CROP_VISUAL_TEMPORAL_COVERAGE_LOW
    CSRF_VALIDATION_FAILED DATABASE_UNAVAILABLE DURATION_MISMATCH EDIT_MODE_INVALID
    EDIT_PLAN_ASSET_BUDGET_EXCEEDED EDIT_PLAN_ASSET_BUDGET_INVALID
    EDIT_PLAN_ASSET_POLICY_BLOCKED EDIT_PLAN_ASSET_POLICY_INVALID
    EDIT_PLAN_CAPABILITY_CONFIG_INVALID EDIT_PLAN_CAPABILITY_UNAVAILABLE
    EDIT_PLAN_CAPABILITY_UNDECLARED EDIT_PLAN_CATALOG_ID_UNKNOWN EDIT_PLAN_CATALOG_INVALID
    EDIT_PLAN_CATALOG_KIND_INVALID EDIT_PLAN_CATALOG_STYLE_MISMATCH
    EDIT_PLAN_CATALOG_TRANSITION_MISMATCH EDIT_PLAN_CATALOG_UNAVAILABLE
    EDIT_PLAN_CATALOG_VERSION_MISMATCH EDIT_PLAN_CLIP_BOUNDS_INVALID
    EDIT_PLAN_CLIP_MISMATCH EDIT_PLAN_EVIDENCE_UNKNOWN
    EDIT_PLAN_GENERATED_ASSET_BUDGET_EXCEEDED EDIT_PLAN_INTENT_MISMATCH
    EDIT_PLAN_INVALID EDIT_PLAN_OVERLAY_BUDGET_EXCEEDED EDIT_PLAN_REGION_OUTSIDE_CLIP
    EDIT_PLAN_REGION_UNKNOWN EDIT_PLAN_REPAIR_EXHAUSTED EDIT_PLAN_SEGMENT_BUDGET_EXCEEDED
    EDIT_PLAN_SOURCE_MISMATCH EDIT_PLAN_STOCK_ASSET_BUDGET_EXCEEDED
    EDIT_PLAN_STOCK_POLICY_BLOCKED EDIT_PLAN_TRACK_OUTSIDE_CLIP EDIT_PLAN_TRACK_UNKNOWN
    EDIT_PLAN_VISUAL_COVERAGE_INSUFFICIENT EDIT_PREFLIGHT_BLOCKED EFFECT_OMITTED
    EFFECT_PLANNING_FAILED EVIDENCE_ARTIFACT_INVALID EVIDENCE_BYTES_LIMIT_EXCEEDED
    EVIDENCE_CANDIDATE_INVALID EVIDENCE_CANDIDATE_MISSING EVIDENCE_CHECKPOINT_INVALID
    EVIDENCE_CONFIG_INVALID EVIDENCE_DURATION_INVALID EVIDENCE_EVENT_INVALID
    EVIDENCE_FRAME_LIMIT_EXCEEDED EVIDENCE_REFERENCE_UNKNOWN EVIDENCE_SOURCE_HASH_INVALID
    EXTERNAL_ASSET_OMITTED
    FILTERGRAPH_TOO_LARGE FILTER_ASSET_KIND_INVALID FILTER_ASSET_UNRESOLVED
    FILTER_AUDIO_REQUIRED FILTER_COLOR_INVALID FILTER_COLOR_TREATMENT_INVALID
    FILTER_CROP_INVALID FILTER_DIMENSIONS_INVALID FILTER_OVERLAY_UNSUPPORTED
    FILTER_POSITION_INVALID FILTER_SEGMENT_LIMIT FILTER_STRATEGY_UNSUPPORTED
    FILTER_SUBTITLE_PATH_INVALID FILTER_TIMELINE_MISMATCH FILTER_TRANSITION_INVALID
    FILTER_TRANSITION_UNSUPPORTED FIRST_SEGMENT_INVALID FRAME_EXECUTION_MISSING
    FRAME_EXTRACTION_FAILED FRAME_EXTRACTION_TIMEOUT FRAME_FFMPEG_UNAVAILABLE
    FRAME_TIMESTAMP_INVALID
    FRAME_QUALITY_CROPDETECT_FAILED FRAME_QUALITY_OUTPUT_MISSING
    FRAME_QUALITY_OUTPUT_TOO_LARGE FRAME_QUALITY_PROBE_FAILED FRAME_QUALITY_PROBE_INVALID
    FRAME_QUALITY_REFERENCE_FAILED FRAME_QUALITY_REFERENCE_INVALID
    FRAME_QUALITY_SIGNAL_FAILED FRAME_QUALITY_TIMEOUT FRAME_QUALITY_TIMEOUT_INVALID
    FRAME_QUALITY_TOOL_UNAVAILABLE FRAME_QUALITY_UNAVAILABLE FRAME_SIGNAL_COLLAPSED
    FRAME_SIGNAL_UNAVAILABLE FROZEN_VIDEO_DETECTED FULL_FRAME_FALLBACK_UNAPPROVED
    IMAGE_ALL_PROVIDERS_FAILED IMAGE_CONFIG_INVALID IMAGE_DISCOVERY_FAILED
    IMAGE_INPUT_INVALID IMAGE_MODELS_UNAVAILABLE INACTIVE_HOOK INVALID_CREDENTIALS
    JOB_INPUT_MISSING JOB_NOT_FOUND JOB_PROCESSING_FAILED JOB_QUEUE_FULL
    JOB_SNAPSHOT_WRITE_FAILED JOB_STATE_UNAVAILABLE LOGIN_RATE_LIMITED
    LONG_SILENCE_DETECTED LONG_SUBTITLE_HOLD LONG_VISUAL_HOLD MAX_CLIPS_INVALID
    MEDIA_HAS_NO_AUDIO MEDIA_PROBE_FAILED MEDIA_PROBE_INVALID MISTRAL_STT_RATE_LIMITED
    MISTRAL_STT_REQUEST_FAILED MISTRAL_STT_TIMEOUT NINEROUTER_CONFIG_INVALID
    NINEROUTER_RATE_LIMITED NINEROUTER_REQUEST_FAILED NINEROUTER_RESPONSE_INCOMPLETE
    NINEROUTER_RESPONSE_INVALID NINEROUTER_RESPONSE_REFUSED
    NINEROUTER_SCHEMA_CAPABILITY_UNVERIFIED NINEROUTER_SCHEMA_MISMATCH
    NINEROUTER_SCHEMA_UNSUPPORTED
    NO_VALID_SHORTS OUTPUT_DIMENSIONS_MISMATCH OVERLAY_BUDGET_EXCEEDED
    OVERLAY_IDS_NOT_UNIQUE OVERLAY_SOURCE_OUTSIDE_CLIP OVERLAY_TRANSITION_TOO_LONG
    PEXELS_CONFIG_INVALID PEXELS_DISABLED PEXELS_DOWNLOAD_FAILED
    PEXELS_DOWNLOAD_REDIRECT_INVALID PEXELS_DOWNLOAD_URL_INVALID
    PEXELS_LICENSE_REVIEW_REQUIRED PEXELS_MEDIA_INVALID PEXELS_MEDIA_TOO_LARGE
    PEXELS_MEDIA_TYPE_INVALID PEXELS_NO_COMPATIBLE_MEDIA
    PEXELS_REDIRECT_LIMIT_EXCEEDED PEXELS_REQUEST_INVALID PEXELS_RESPONSE_INVALID
    PEXELS_RESPONSE_TOO_LARGE PEXELS_SEARCH_FAILED PLANNED_OPERATIONS_MISSING
    PROMPT_INVALID PROMPT_REQUIRED PROMPT_VERSION_NOT_FOUND QA_CLIP_LIMIT_REACHED
    QA_CONFIG_INVALID QA_MEDIA_OUTPUT_TOO_LARGE QA_MEDIA_TOOL_TIMEOUT
    QA_MEDIA_TOOL_UNAVAILABLE QA_OUTPUT_MISSING QA_TIMEOUT_INVALID QA_VIDEO_INVALID
    REFERENCE_QUALITY_CATASTROPHIC REGION_REFERENCE_OUTSIDE_CLIP
    REGION_REFERENCE_UNKNOWN REMOTE_IMAGE_REQUEST_FAILED RENDER_ACTIVITY_CALLBACK_FAILED
    RENDER_CRF_INVALID RENDER_FPS_CAP_INVALID RENDER_FPS_INVALID RENDER_PREFLIGHT_FALLBACK
    RENDER_PRESET_INVALID RENDER_PROMOTION_BLOCKED RENDER_PROMOTION_CONFIG_INVALID
    RENDER_QUALITY_PROFILE_INVALID RENDER_STRUCTURE_UNAVAILABLE REQUEST_ORIGIN_INVALID
    REQUESTED_ASSETS_MISSING REQUIRED_GENERATED_ASSET_COUNT_INVALID
    REQUIRED_STOCK_ASSET_COUNT_INVALID RHYTHM_EVIDENCE_UNAVAILABLE
    SCENE_DETECTION_FAILED SCENE_DETECTION_TIMEOUT SCENE_FFMPEG_UNAVAILABLE
    SEMANTIC_QA_FRAMES_MISSING SEMANTIC_QA_RESPONSE_INVALID SEMANTIC_REVIEW_REQUESTED
    SEMANTIC_REVIEW_UNAVAILABLE SEGMENT_BUDGET_EXCEEDED SEGMENT_IDS_NOT_UNIQUE
    SEGMENT_SOURCE_OUTSIDE_CLIP SEGMENT_TIMELINE_GAP SESSION_ACTIVE_JOBS
    SESSION_NOT_FOUND SESSION_SOURCE_CHANGED SESSION_SOURCE_EXPIRED
    SESSION_SOURCE_IMMUTABLE SESSION_SOURCE_NOT_FOUND SESSION_SOURCE_UNAVAILABLE
    SEVERE_BLOCKINESS_REVIEW SEVERE_BLUR_REVIEW SHORTS_PLAN_ARTIFACT_INVALID
    SHORTS_RESPONSE_INVALID SOURCE_DURATION_INVALID SOURCE_UPLOAD_BUSY
    SOURCE_UPLOAD_FAILED SOURCE_UPLOAD_NOT_FOUND SOURCE_VALIDATION_STORAGE_FAILED
    SOURCE_VALIDATION_TIMEOUT SOURCE_VALIDATION_UNAVAILABLE SOURCE_VIDEO_INVALID
    STOCK_ASSET_KIND_INVALID STOCK_ASSET_LIMIT_INVALID STOCK_POLICY_BLOCKED
    STOCK_POLICY_INVALID STT_ALL_PROVIDERS_FAILED STT_CONFIG_INVALID STT_INPUT_MISSING
    STT_LANGUAGE_UNSUPPORTED SUBTITLE_GAP_REVIEW SUBTITLE_SAFE_ZONE_CONFLICT
    SUBTITLE_TIMELINE_UNAVAILABLE TRACK_REFERENCE_OUTSIDE_CLIP
    TRACK_REFERENCE_UNKNOWN TRANSITION_FALLBACK TRANSITION_TOO_LONG UNAUTHENTICATED
    UNEXPLAINED_FALLBACK UNPLANNED_OPERATIONS_EXECUTED UNREQUESTED_ASSETS_USED
    UPLOAD_CANCELLED UPLOAD_CHUNK_INVALID UPLOAD_CHUNK_TIMEOUT UPLOAD_METADATA_CONFLICT
    UPLOAD_OFFSET_MISMATCH UPLOAD_SIZE_INVALID UPLOAD_STATE_INVALID UPLOAD_TOO_LARGE
    VIDEO_CODEC_UNEXPECTED VIDEO_PROBE_FAILED VIDEO_PROBE_INVALID VIDEO_RENDER_FAILED
    VIDEO_TYPE_UNSUPPORTED VISUAL_FRAME_DUPLICATE VISUAL_FRAME_TIMING_INVALID
    VISUAL_FRAME_UNKNOWN VISUAL_REFRAME_FALLBACK VISUAL_REGION_DUPLICATE
    VISUAL_REGION_UNKNOWN VISUAL_RESPONSE_INVALID VISUAL_SCENE_DUPLICATE
    VISUAL_SCENE_REGION_INVALID VISUAL_SCENE_UNKNOWN VISUAL_SCOPE_COLLISION
    VISUAL_TRACK_DUPLICATE VISUAL_TRACK_ROLE_INVALID VISUAL_TRACK_TIMING_INVALID
    FFMPEGA_CONFIG_INVALID FFMPEGA_EXECUTION_FAILED FFMPEGA_HISTORY_FAILED
    FFMPEGA_INPUT_MISSING FFMPEGA_OUTPUT_MISSING FFMPEGA_PARAMETER_BLOCKED
    FFMPEGA_PATH_NOT_SHARED FFMPEGA_PLAN_EMPTY FFMPEGA_PLAN_INVALID
    FFMPEGA_QUEUE_FAILED FFMPEGA_RESPONSE_INVALID FFMPEGA_SKILL_BLOCKED
    ACTIVITY_STORAGE_UNAVAILABLE ARTIFACT_NOT_FOUND ARTIFACT_PATH_INVALID
    AUDIT_OPERATION_FAILED CHECKPOINT_FILE_UNAVAILABLE COMPOSITION_CONFIG_INVALID
    FFPROBE_TIMEOUT FFPROBE_UNAVAILABLE FRAME_BYTES_LIMIT_INVALID FRAME_CLIP_INVALID
    FRAME_CLIP_LIMIT_INVALID FRAME_DIMENSIONS_INVALID FRAME_FOCUS_INVALID
    FRAME_FOCUS_LIMIT_INVALID FRAME_ID_PREFIX_INVALID FRAME_LIMIT_INVALID
    FRAME_SOURCE_INVALID FRAME_TOO_LARGE GENERATED_ASSET_LIMIT_INVALID
    PROMPT_VERSION_SERVICE_UNAVAILABLE RETENTION_BUSY RETENTION_OPERATION_FAILED
    RETENTION_UNAVAILABLE SCENE_BOUNDARY_INVALID SCENE_DURATION_INVALID
    SCENE_GAP_INVALID SCENE_LIMIT_INVALID SCENE_OUTPUT_INVALID SCENE_THRESHOLD_INVALID
    SEMANTIC_QA_UNAVAILABLE SESSION_MEDIA_UNAVAILABLE SESSION_SOURCE_PATH_INVALID
    SOURCE_EXPIRED UPLOAD_CHUNK_TYPE_UNSUPPORTED UPLOAD_EXPIRED UPLOAD_INCOMPLETE
    UPLOAD_OFFSET_INVALID UPLOAD_PATH_INVALID UPLOAD_WRITE_FAILED
    FFMPEGA_TIMEOUT FFMPEGA_UNAVAILABLE
    REPAIR_CANDIDATE_MISSING REPAIR_CANDIDATE_TOO_LARGE
    REPAIR_CLIP_LIMIT_EXCEEDED REPAIR_CODE_LIMIT_EXCEEDED
    REPAIR_CONTEXT_INVALID REPAIR_CONTEXT_PRIVATE REPAIR_EVIDENCE_INVALID
    REPAIR_EVIDENCE_LIMIT_EXCEEDED REPAIR_MODE_INVALID REPAIR_NOT_ELIGIBLE
    REPAIR_ATTEMPT_REQUIRED REPAIR_EXECUTION_DRY_RUN_FAILED
    REPAIR_DEFECT_UNRESOLVED REPAIR_MUTATION_OUTSIDE_ALLOWLIST
    REPAIR_PLAN_CALL_LIMIT_EXCEEDED REPAIR_PLAN_FINGERPRINT_INVALID
    REPAIR_ROUND_INVALID REPAIR_SAFE_BASELINE_INVALID
    REPAIR_PROMPT_INVALID REPAIR_REPORT_INVALID REPAIR_REPORT_TOO_LARGE
    REPAIR_REQUEST_TOO_LARGE REPAIR_TRANSCRIPT_INVALID REPAIR_TRANSCRIPT_TOO_LARGE
    RENDER_EVIDENCE_UNAVAILABLE
    """
)


REGISTRY_V1_EXCLUSIONS = MappingProxyType({
    code: reason
    for code, reason in {
        "ACTIVITY_CATEGORY_INVALID": "internal public-activity schema validation",
        "ACTIVITY_COUNT_INVALID": "internal public-activity schema validation",
        "ACTIVITY_ERROR_INVALID": "internal public-activity schema validation",
        "ACTIVITY_FAILURE_INVALID": "internal public-activity schema validation",
        "ACTIVITY_FIELD_INVALID": "internal public-activity schema validation",
        "ACTIVITY_LABEL_INVALID": "internal public-activity schema validation",
        "ACTIVITY_MESSAGE_INVALID": "internal public-activity schema validation",
        "ACTIVITY_PROGRESS_INVALID": "internal public-activity schema validation",
        "ACTIVITY_RETRY_INVALID": "internal public-activity schema validation",
        "ACTIVITY_STATUS_INVALID": "internal public-activity schema validation",
        "ACTIVITY_VALUE_INVALID": "internal public-activity schema validation",
        "ADMIN_COMMAND_INVALID": "operator CLI validation",
        "ADMIN_INPUT_FAILED": "operator CLI input handling",
        "ARTIFACT_PREVIEW_UNSUPPORTED": "artifact preview request validation",
        "AUDIT_BATCH_INVALID": "operator audit batch validation",
        "AUDIT_COMMAND_INVALID": "operator CLI validation",
        "AUDIT_CONFIG_INVALID": "operator audit configuration validation",
        "AUDIT_FILTER_INVALID": "operator audit query validation",
        "AUDIT_HOLD_INVALID": "operator audit hold validation",
        "AUDIT_REVIEW_INVALID": "operator audit review validation",
        "CHECKPOINT_CONFIG_INVALID": "deployment configuration validation",
        "CURSOR_INVALID": "bounded API/CLI pagination validation",
        "DATABASE_CONFIG_INVALID": "operator database configuration validation",
        "DOCUMENT_INVALID": "operator audit document validation",
        "DOCUMENT_MISSING": "operator audit document validation",
        "DOCUMENT_TOO_LARGE": "operator audit document validation",
        "DOCUMENT_TYPE_UNSUPPORTED": "operator audit document validation",
        "EVENT_CURSOR_INVALID": "bounded activity pagination validation",
        "FAVORITE_RUN_INVALID": "workspace request validation",
        "IMPORT_BATCH_INVALID": "operator legacy-import validation",
        "IMPORT_ROOT_INVALID": "operator legacy-import path validation",
        "JOB_CONFIG_INVALID": "deployment configuration validation",
        "JOB_ID_INVALID": "internal identifier validation",
        "JSON_INVALID": "operator audit document validation",
        "MANIFEST_MISSING": "operator audit document validation",
        "OUTPUT_CLIP_INVALID": "operator audit document validation",
        "OUTPUT_ENTRY_INVALID": "operator audit document validation",
        "PAGE_LIMIT_INVALID": "bounded API/CLI pagination validation",
        "PRIOR_ATTEMPT_NOT_FOUND": "workspace retry request validation",
        "PRIOR_ATTEMPT_REQUIRED": "workspace retry request validation",
        "PRIOR_QUALITY_EVIDENCE_UNAVAILABLE": "workspace retry request validation",
        "PRIOR_QUALITY_FEEDBACK_FLAG_REQUIRED": "workspace retry request validation",
        "PROMPT_RUN_CONFLICT": "workspace request conflict validation",
        "PROMPT_RUN_TIMEOUT": "operator workspace rerun wait timeout",
        "PROMPT_VERSION_CONFLICT": "workspace request conflict validation",
        "PROMPT_VERSION_ID_INVALID": "internal identifier validation",
        "RETENTION_BATCH_INVALID": "operator retention batch validation",
        "RETENTION_CONFIG_INVALID": "operator retention configuration validation",
        "RETENTION_COMMAND_INVALID": "operator CLI validation",
        "RETENTION_HOLD_INVALID": "operator retention hold validation",
        "RETENTION_PATH_INVALID": "operator retention path validation",
        "SESSION_ID_INVALID": "internal identifier validation",
        "SESSION_MEDIA_CONFIG_INVALID": "deployment configuration validation",
        "SESSION_REQUIRED": "workspace request validation",
        "SESSION_TITLE_INVALID": "workspace request validation",
        "SESSION_TITLE_REQUIRED": "workspace request validation",
        "SESSION_WORKFLOW_VERSION_INVALID": "workspace request validation",
        "SESSION_WORKFLOW_VERSION_UNKNOWN": "operator workspace inventory validation",
        "SRT_INVALID": "operator audit document validation",
        "VIDEO_ARTIFACT_MISSING": "operator audit verification finding",
        "WORKSPACE_COMMAND_INVALID": "operator CLI validation",
        "WORKSPACE_BACKFILL_BUSY": "operator workspace backfill state",
        "WORKSPACE_BACKFILL_INVALID": "operator workspace backfill validation",
        "WORKSPACE_RERUN_INVALID": "operator workspace rerun validation",
    }.items()
})


_TECHNICAL_CODES = _code_set(
    """
    ACTIVE_PICTURE_UNAVAILABLE AUDIO_MISSING BLACK_FRAMES_DETECTED DURATION_MISMATCH
    FRAME_EXECUTION_MISSING FRAME_QUALITY_CROPDETECT_FAILED FRAME_QUALITY_OUTPUT_MISSING
    FRAME_QUALITY_OUTPUT_TOO_LARGE FRAME_QUALITY_PROBE_FAILED FRAME_QUALITY_PROBE_INVALID
    FRAME_QUALITY_REFERENCE_FAILED FRAME_QUALITY_REFERENCE_INVALID
    FRAME_QUALITY_SIGNAL_FAILED FRAME_QUALITY_TIMEOUT FRAME_QUALITY_TIMEOUT_INVALID
    FRAME_QUALITY_TOOL_UNAVAILABLE FRAME_QUALITY_UNAVAILABLE FRAME_SIGNAL_COLLAPSED
    FRAME_SIGNAL_UNAVAILABLE FROZEN_VIDEO_DETECTED LONG_SILENCE_DETECTED
    OUTPUT_DIMENSIONS_MISMATCH QA_MEDIA_OUTPUT_TOO_LARGE QA_MEDIA_TOOL_TIMEOUT
    QA_MEDIA_TOOL_UNAVAILABLE QA_OUTPUT_MISSING QA_VIDEO_INVALID
    REFERENCE_QUALITY_CATASTROPHIC RENDER_STRUCTURE_UNAVAILABLE
    CREATIVE_CONFORMANCE_UNAVAILABLE VIDEO_CODEC_UNEXPECTED FFPROBE_TIMEOUT
    FFPROBE_UNAVAILABLE REPAIR_ATTEMPT_REQUIRED REPAIR_EXECUTION_DRY_RUN_FAILED
    REPAIR_PLAN_CALL_LIMIT_EXCEEDED REPAIR_PLAN_FINGERPRINT_INVALID
    REPAIR_ROUND_INVALID REPAIR_SAFE_BASELINE_INVALID
    """
)

_ADVISORY_CODES = _code_set(
    """
    ATTENTION_GAP FALLBACKS_USED INACTIVE_HOOK LONG_SUBTITLE_HOLD LONG_VISUAL_HOLD
    RHYTHM_EVIDENCE_UNAVAILABLE SEMANTIC_REVIEW_REQUESTED SEMANTIC_REVIEW_UNAVAILABLE
    SEMANTIC_QA_UNAVAILABLE SEVERE_BLOCKINESS_REVIEW SEVERE_BLUR_REVIEW
    SUBTITLE_GAP_REVIEW
    SUBTITLE_TIMELINE_UNAVAILABLE UNPLANNED_OPERATIONS_EXECUTED
    PREDICTIVE_ATTENTION_GAP_RISK PREDICTIVE_INACTIVE_HOOK_RISK
    PREDICTIVE_LONG_VISUAL_HOLD_RISK PREDICTIVE_RHYTHM_RISK
    """
)

_VISUAL_REPAIR_CODES = _code_set(
    """
    VISUAL_FRAME_DUPLICATE VISUAL_FRAME_TIMING_INVALID VISUAL_FRAME_UNKNOWN
    VISUAL_REGION_DUPLICATE VISUAL_REGION_UNKNOWN VISUAL_RESPONSE_INVALID
    VISUAL_SCENE_DUPLICATE VISUAL_SCENE_REGION_INVALID VISUAL_SCENE_UNKNOWN
    VISUAL_SCOPE_COLLISION VISUAL_TRACK_DUPLICATE VISUAL_TRACK_ROLE_INVALID
    VISUAL_TRACK_TIMING_INVALID
    """
)

_PLAN_REPAIR_CODES = _code_set(
    """
    ASSET_BUDGET_EXCEEDED CAPABILITY_UNAVAILABLE CAPABILITY_UNDECLARED
    COMPOSITION_CROP_TARGET_TOO_WIDE COMPOSITION_LAYOUT_UNSUPPORTED
    EDIT_PLAN_ASSET_BUDGET_EXCEEDED EDIT_PLAN_CAPABILITY_UNAVAILABLE
    EDIT_PLAN_CAPABILITY_UNDECLARED EDIT_PLAN_CATALOG_ID_UNKNOWN
    EDIT_PLAN_CATALOG_KIND_INVALID EDIT_PLAN_CATALOG_STYLE_MISMATCH
    EDIT_PLAN_CATALOG_TRANSITION_MISMATCH EDIT_PLAN_CLIP_BOUNDS_INVALID
    EDIT_PLAN_CLIP_MISMATCH EDIT_PLAN_EVIDENCE_UNKNOWN
    EDIT_PLAN_GENERATED_ASSET_BUDGET_EXCEEDED EDIT_PLAN_INTENT_MISMATCH
    EDIT_PLAN_INVALID EDIT_PLAN_OVERLAY_BUDGET_EXCEEDED EDIT_PLAN_REGION_OUTSIDE_CLIP
    EDIT_PLAN_REGION_UNKNOWN EDIT_PLAN_SEGMENT_BUDGET_EXCEEDED
    EDIT_PLAN_STOCK_ASSET_BUDGET_EXCEEDED EDIT_PLAN_TRACK_OUTSIDE_CLIP
    EDIT_PLAN_TRACK_UNKNOWN EVIDENCE_REFERENCE_UNKNOWN FULL_FRAME_FALLBACK_UNAPPROVED
    OVERLAY_BUDGET_EXCEEDED OVERLAY_TRANSITION_TOO_LONG REGION_REFERENCE_OUTSIDE_CLIP
    REGION_REFERENCE_UNKNOWN SEGMENT_BUDGET_EXCEEDED SUBTITLE_SAFE_ZONE_CONFLICT
    TRACK_REFERENCE_OUTSIDE_CLIP TRACK_REFERENCE_UNKNOWN TRANSITION_TOO_LONG
    CROP_VISUAL_GAP_TOO_LARGE CROP_VISUAL_OBSERVATION_MISSING
    CROP_VISUAL_OBSERVATIONS_INSUFFICIENT CROP_VISUAL_TEMPORAL_COVERAGE_LOW
    PREDICTIVE_ACTIVE_PICTURE_RISK PREDICTIVE_OVERLAY_DUPLICATE
    PREDICTIVE_OVERLAY_GEOMETRY_INVALID PREDICTIVE_OVERLAY_OPACITY_LOW
    PREDICTIVE_OVERLAY_TIMING_INVALID PREDICTIVE_SUBTITLE_SAFE_ZONE_CONFLICT
    """
)

_CONDITIONAL_REPAIR_CODES = _code_set(
    """
    ACTIVE_PICTURE_TOO_SMALL CREATIVE_INTENT_UNMET PLANNED_OPERATIONS_MISSING
    REQUESTED_ASSETS_MISSING UNEXPLAINED_FALLBACK UNREQUESTED_ASSETS_USED
    """
)

_FALLBACK_CODES = _code_set(
    """
    CAPTION_SAFE_ZONE_FALLBACK EFFECT_OMITTED EXTERNAL_ASSET_OMITTED
    RENDER_PREFLIGHT_FALLBACK TRANSITION_FALLBACK VISUAL_REFRAME_FALLBACK
    EFFECT_PLANNING_FAILED FFMPEGA_CONFIG_INVALID FFMPEGA_EXECUTION_FAILED
    FFMPEGA_HISTORY_FAILED FFMPEGA_INPUT_MISSING FFMPEGA_OUTPUT_MISSING
    FFMPEGA_PARAMETER_BLOCKED FFMPEGA_PATH_NOT_SHARED FFMPEGA_PLAN_EMPTY
    FFMPEGA_PLAN_INVALID FFMPEGA_QUEUE_FAILED FFMPEGA_RESPONSE_INVALID
    FFMPEGA_SKILL_BLOCKED FFMPEGA_TIMEOUT FFMPEGA_UNAVAILABLE
    REPAIR_CAPABILITY_UNSUPPORTED REPAIR_CATALOG_STYLE_LOST
    REPAIR_DEFECT_UNRESOLVED REPAIR_MUTATION_OUTSIDE_ALLOWLIST
    REPAIR_NEW_DEFECT_INTRODUCED REPAIR_OUTPUT_COUNT_CHANGED
    REPAIR_SOURCE_WINDOW_CHANGED REPAIR_SUBTITLE_REQUIREMENT_LOST
    REPAIR_UNAFFECTED_OPERATION_REMOVED
    """
)

_PREDICTIVE_METADATA: dict[str, tuple[str, tuple[str, ...], str, bool]] = {
    "PREDICTIVE_OVERLAY_DUPLICATE": (
        "plan_overlay_identity",
        ("edit_plan", "overlay_ids"),
        "duplicate overlay identifier",
        True,
    ),
    "PREDICTIVE_OVERLAY_OPACITY_LOW": (
        "plan_overlay_opacity",
        ("edit_plan", "overlay_opacity"),
        "opacity < 0.15",
        True,
    ),
    "PREDICTIVE_OVERLAY_TIMING_INVALID": (
        "plan_overlay_timing",
        ("edit_plan", "timeline_windows"),
        "overlay outside its segment or non-positive duration",
        True,
    ),
    "PREDICTIVE_OVERLAY_GEOMETRY_INVALID": (
        "plan_overlay_geometry",
        ("edit_plan", "overlay_geometry"),
        "width_ratio + 2 * margin_ratio > 1",
        True,
    ),
    "PREDICTIVE_SUBTITLE_SAFE_ZONE_CONFLICT": (
        "plan_subtitle_safe_zone",
        ("edit_plan", "overlay_position"),
        "protected overlay occupies a bottom subtitle zone",
        True,
    ),
    "PREDICTIVE_ACTIVE_PICTURE_RISK": (
        "plan_active_picture",
        ("edit_plan", "source_aspect_ratio"),
        "predicted active height ratio < 0.35",
        True,
    ),
    "PREDICTIVE_INACTIVE_HOOK_RISK": (
        "plan_hook_activity",
        ("edit_plan", "opening_operations"),
        "no visible opening operation in first 3000 ms",
        False,
    ),
    "PREDICTIVE_ATTENTION_GAP_RISK": (
        "plan_attention_gap",
        ("edit_plan", "segment_operations"),
        "operation-free interval >= 6000 ms",
        False,
    ),
    "PREDICTIVE_LONG_VISUAL_HOLD_RISK": (
        "plan_visual_hold",
        ("edit_plan", "segment_duration"),
        "static segment duration >= 8000 ms",
        False,
    ),
    "PREDICTIVE_RHYTHM_RISK": (
        "plan_rhythm",
        ("edit_plan", "segment_count"),
        "single segment duration >= 12000 ms",
        False,
    ),
}

_POST_RENDER_FALLBACK_CODES = _code_set(
    """
    ASSET_OVERLAY_DUPLICATED ASSET_OVERLAY_NOT_VISIBLE
    ASSET_OVERLAY_OPACITY_TOO_LOW ASSET_VISIBILITY_ANALYSIS_UNAVAILABLE
    ASSET_VISIBILITY_ASSET_INVALID ASSET_VISIBILITY_ASSET_UNRESOLVED
    ASSET_VISIBILITY_GEOMETRY_INVALID ASSET_VISIBILITY_LIMIT_REACHED
    ASSET_VISIBILITY_TIMING_INVALID CAPTION_HEIGHT_EXCEEDED
    CAPTION_OUTSIDE_FOOTER_SAFE_ZONE CAPTION_OUTSIDE_FRAME_SAFE_ZONE
    CAPTION_WIDTH_EXCEEDED
    """
)

_PROVIDER_RETRY_CODES = _code_set(
    """
    ASSET_PROVIDER_UNAVAILABLE IMAGE_ALL_PROVIDERS_FAILED IMAGE_DISCOVERY_FAILED
    IMAGE_MODELS_UNAVAILABLE MISTRAL_STT_RATE_LIMITED MISTRAL_STT_REQUEST_FAILED
    MISTRAL_STT_TIMEOUT NINEROUTER_RATE_LIMITED NINEROUTER_REQUEST_FAILED
    NINEROUTER_RESPONSE_INCOMPLETE NINEROUTER_RESPONSE_INVALID
    NINEROUTER_SCHEMA_MISMATCH PEXELS_DOWNLOAD_FAILED PEXELS_SEARCH_FAILED
    REMOTE_IMAGE_REQUEST_FAILED STT_ALL_PROVIDERS_FAILED FFMPEGA_TIMEOUT
    FFMPEGA_UNAVAILABLE
    """
)

_LEGACY_RETRYABLE_CODES = _code_set(
    """
    DATABASE_UNAVAILABLE EDIT_PLAN_VISUAL_COVERAGE_INSUFFICIENT JOB_STATE_UNAVAILABLE
    MISTRAL_STT_REQUEST_FAILED MISTRAL_STT_RATE_LIMITED NINEROUTER_REQUEST_FAILED
    NINEROUTER_RATE_LIMITED PEXELS_SEARCH_FAILED PEXELS_DOWNLOAD_FAILED
    REMOTE_IMAGE_REQUEST_FAILED RENDER_PROMOTION_BLOCKED RETENTION_BUSY
    """
)

_PUBLIC_CODES = _code_set(
    """
    AUTH_UNAVAILABLE UNAUTHENTICATED INVALID_CREDENTIALS LOGIN_RATE_LIMITED
    REQUEST_ORIGIN_INVALID CSRF_VALIDATION_FAILED DATABASE_UNAVAILABLE SESSION_NOT_FOUND
    SESSION_ACTIVE_JOBS SESSION_SOURCE_NOT_FOUND SESSION_SOURCE_UNAVAILABLE
    SESSION_SOURCE_EXPIRED SESSION_SOURCE_IMMUTABLE SESSION_SOURCE_CHANGED
    VIDEO_TYPE_UNSUPPORTED UPLOAD_SIZE_INVALID UPLOAD_TOO_LARGE
    UPLOAD_METADATA_CONFLICT UPLOAD_OFFSET_MISMATCH UPLOAD_CHUNK_INVALID
    UPLOAD_CHUNK_TIMEOUT
    UPLOAD_STATE_INVALID SOURCE_UPLOAD_BUSY SOURCE_UPLOAD_NOT_FOUND
    SOURCE_UPLOAD_FAILED SOURCE_VALIDATION_UNAVAILABLE SOURCE_VALIDATION_TIMEOUT
    SOURCE_VIDEO_INVALID SOURCE_VALIDATION_STORAGE_FAILED UPLOAD_CANCELLED
    PROMPT_REQUIRED PROMPT_INVALID JOB_QUEUE_FULL JOB_NOT_FOUND
    PROMPT_VERSION_NOT_FOUND NINEROUTER_REQUEST_FAILED NINEROUTER_RATE_LIMITED
    MISTRAL_STT_REQUEST_FAILED MISTRAL_STT_RATE_LIMITED PEXELS_SEARCH_FAILED
    REMOTE_IMAGE_REQUEST_FAILED CREATIVE_INTENT_CAPABILITY_UNAVAILABLE
    EDIT_PLAN_INTENT_MISMATCH EDIT_PLAN_REPAIR_EXHAUSTED
    EDIT_PLAN_VISUAL_COVERAGE_INSUFFICIENT REQUIRED_GENERATED_ASSET_COUNT_INVALID
    REQUIRED_STOCK_ASSET_COUNT_INVALID ACTIVITY_STREAM_UNAVAILABLE
    ACTIVITY_STORAGE_UNAVAILABLE ARTIFACT_NOT_FOUND PROMPT_VERSION_SERVICE_UNAVAILABLE
    RETENTION_BUSY RETENTION_UNAVAILABLE SESSION_MEDIA_UNAVAILABLE SOURCE_EXPIRED
    UPLOAD_CHUNK_TYPE_UNSUPPORTED UPLOAD_EXPIRED UPLOAD_INCOMPLETE
    UPLOAD_OFFSET_INVALID UPLOAD_PATH_INVALID UPLOAD_WRITE_FAILED
    """
) | _TECHNICAL_CODES | _ADVISORY_CODES | _PLAN_REPAIR_CODES | _CONDITIONAL_REPAIR_CODES | _FALLBACK_CODES


_DOMAIN_LABELS = {
    DefectDomain.ACTIVITY: ("activity", "actividad"),
    DefectDomain.ASSET: ("asset handling", "recursos visuales"),
    DefectDomain.CAPTION: ("captions", "subtitulos"),
    DefectDomain.CATALOG: ("creative catalog", "catalogo creativo"),
    DefectDomain.EVIDENCE: ("visual evidence", "evidencia visual"),
    DefectDomain.INFRASTRUCTURE: ("infrastructure", "infraestructura"),
    DefectDomain.OUTCOME: ("outcome evaluation", "evaluacion del resultado"),
    DefectDomain.PLANNING: ("edit planning", "planificacion de edicion"),
    DefectDomain.PROVIDER: ("remote provider", "proveedor remoto"),
    DefectDomain.RENDER: ("rendering", "renderizado"),
    DefectDomain.SECURITY: ("access control", "control de acceso"),
    DefectDomain.SOURCE: ("source media", "video fuente"),
    DefectDomain.UNKNOWN: ("unknown stage", "etapa desconocida"),
    DefectDomain.WORKSPACE: ("workspace", "espacio de trabajo"),
}


_PRESENTATION_OVERRIDES: dict[str, tuple[str, str, str, str]] = {
    "ACTIVE_PICTURE_TOO_SMALL": (
        "Active picture is too small",
        "The rendered subject occupies too little of the vertical frame.",
        "La imagen activa es demasiado pequena",
        "El sujeto renderizado ocupa muy poco del encuadre vertical.",
    ),
    "AUDIO_MISSING": (
        "Audio is missing",
        "The rendered output does not contain the required audio stream.",
        "Falta el audio",
        "La salida renderizada no contiene el flujo de audio requerido.",
    ),
    "CAPTION_SAFE_ZONE_FALLBACK": (
        "Caption safe-zone fallback",
        "An overlay was moved to preserve subtitle readability.",
        "Ajuste por zona segura de subtitulos",
        "Se movio una capa para conservar la legibilidad de los subtitulos.",
    ),
    "EFFECT_OMITTED": (
        "Optional effect omitted",
        "An optional effect was omitted while preserving the native render.",
        "Efecto opcional omitido",
        "Se omitio un efecto opcional y se conservo el render nativo.",
    ),
    "EXTERNAL_ASSET_OMITTED": (
        "Optional asset omitted",
        "An unavailable optional asset was replaced with source media.",
        "Recurso opcional omitido",
        "Un recurso opcional no disponible se reemplazo con el video fuente.",
    ),
    "RENDER_PREFLIGHT_FALLBACK": (
        "Render preflight fallback",
        "The edit was simplified after deterministic FFmpeg preflight failed.",
        "Fallback de preflight de render",
        "La edicion se simplifico despues de fallar el preflight determinista de FFmpeg.",
    ),
    "TRANSITION_FALLBACK": (
        "Transition fallback",
        "An unsupported transition sequence was replaced with safe cuts.",
        "Fallback de transicion",
        "Una secuencia de transicion no compatible se reemplazo con cortes seguros.",
    ),
    "VISUAL_REFRAME_FALLBACK": (
        "Visual reframe fallback",
        "An unsafe crop was replaced with a content-preserving fit.",
        "Fallback de reencuadre visual",
        "Un recorte inseguro se reemplazo con un ajuste que conserva el contenido.",
    ),
}


def _domain(code: str) -> DefectDomain:
    if code.startswith("ACTIVITY_"):
        return DefectDomain.ACTIVITY
    if code in {
        "ARTIFACT_PATH_INVALID",
        "SESSION_SOURCE_PATH_INVALID",
        "UPLOAD_PATH_INVALID",
    }:
        return DefectDomain.SECURITY
    if code.startswith(("AUTH_", "CSRF_", "REQUEST_ORIGIN", "UNAUTHENTICATED", "INVALID_CREDENTIALS", "LOGIN_")):
        return DefectDomain.SECURITY
    if code.startswith(("SESSION_SOURCE", "SESSION_MEDIA", "SOURCE_", "UPLOAD_", "VIDEO_TYPE", "MEDIA_HAS_NO_AUDIO", "AUDIO_EXTRACTION", "STT_INPUT")):
        return DefectDomain.SOURCE
    if code.startswith(("SESSION_", "JOB_", "PROMPT_", "ARTIFACT_")):
        return DefectDomain.WORKSPACE
    if code.startswith(("NINEROUTER_", "MISTRAL_", "STT_", "IMAGE_", "PEXELS_", "REMOTE_IMAGE")):
        return DefectDomain.PROVIDER
    if code.startswith("CATALOG_"):
        return DefectDomain.CATALOG
    if code.startswith(("ASSET_", "STOCK_", "GENERATED_ASSET", "CREATIVE_INTENT")):
        return DefectDomain.ASSET
    if code.startswith(("CAPTION_", "SUBTITLE_")):
        return DefectDomain.CAPTION
    if code.startswith(("VISUAL_", "CROP_VISUAL", "FRAME_", "SCENE_")):
        return DefectDomain.EVIDENCE
    if code.startswith(("EDIT_", "CLIP_", "SEGMENT_", "OVERLAY_", "REGION_", "TRACK_", "CAPABILITY_", "TRANSITION_", "SHORTS_", "NO_VALID_SHORTS", "FULL_FRAME", "EVIDENCE_", "FIRST_SEGMENT", "REPAIR_")):
        return DefectDomain.PLANNING
    if code.startswith(("RENDER_", "FILTER", "COMPOSITION_", "FFMPEGA_", "VIDEO_RENDER", "MEDIA_PROBE", "FFPROBE", "EFFECT_", "EXTERNAL_ASSET_OMITTED")):
        return DefectDomain.RENDER
    if code.startswith(("QA_", "ACTIVE_PICTURE", "REFERENCE_QUALITY", "BLACK_", "FROZEN_", "LONG_", "ATTENTION_", "INACTIVE_", "SEMANTIC_", "RHYTHM_", "PLANNED_", "REQUESTED_", "UNREQUESTED_", "UNPLANNED_", "UNEXPLAINED_", "SEVERE_", "AUDIO_", "OUTPUT_", "VIDEO_CODEC", "DURATION_", "CREATIVE_")):
        return DefectDomain.OUTCOME
    if code.startswith(("DATABASE_", "CHECKPOINT_", "AUDIT_", "RETENTION_")):
        return DefectDomain.INFRASTRUCTURE
    return DefectDomain.OUTCOME


def _repair_strategy(code: str) -> RepairStrategy:
    if code in _VISUAL_REPAIR_CODES:
        return RepairStrategy.LLM_VISUAL_REPAIR
    if code in _PLAN_REPAIR_CODES:
        return RepairStrategy.LLM_PLAN_REPAIR
    if code in _CONDITIONAL_REPAIR_CODES:
        return RepairStrategy.CONDITIONAL_LLM_OR_FALLBACK
    if code in _POST_RENDER_FALLBACK_CODES:
        return RepairStrategy.DETERMINISTIC_FALLBACK
    if code in _FALLBACK_CODES:
        return RepairStrategy.DETERMINISTIC_FALLBACK
    if code in _PROVIDER_RETRY_CODES:
        return RepairStrategy.PROVIDER_RETRY
    if code in _TECHNICAL_CODES:
        return RepairStrategy.RENDERER_RETRY_OR_FAIL
    if code in _ADVISORY_CODES:
        return RepairStrategy.ADVISORY
    return RepairStrategy.TERMINAL


def _repair_phase(code: str, strategy: RepairStrategy) -> RepairPhase:
    if code in _PREDICTIVE_METADATA:
        return RepairPhase.PRE_RENDER
    if code in _POST_RENDER_FALLBACK_CODES:
        return RepairPhase.POST_RENDER
    return {
        RepairStrategy.LLM_VISUAL_REPAIR: RepairPhase.VISUAL_UNDERSTANDING,
        RepairStrategy.LLM_PLAN_REPAIR: RepairPhase.PRE_RENDER,
        RepairStrategy.CONDITIONAL_LLM_OR_FALLBACK: RepairPhase.PRE_RENDER,
        RepairStrategy.DETERMINISTIC_FALLBACK: RepairPhase.COMPILE,
        RepairStrategy.PROVIDER_RETRY: RepairPhase.TRANSPORT,
        RepairStrategy.RENDERER_RETRY_OR_FAIL: RepairPhase.POST_RENDER,
        RepairStrategy.ADVISORY: RepairPhase.POST_RENDER,
        RepairStrategy.TERMINAL: RepairPhase.NONE,
    }[strategy]


def _promotion_class(code: str, strategy: RepairStrategy) -> PromotionClass:
    if code in _TECHNICAL_CODES:
        return PromotionClass.TECHNICAL_BLOCKER
    if strategy is RepairStrategy.ADVISORY:
        return PromotionClass.ADVISORY
    if strategy in {
        RepairStrategy.LLM_PLAN_REPAIR,
        RepairStrategy.CONDITIONAL_LLM_OR_FALLBACK,
        RepairStrategy.DETERMINISTIC_FALLBACK,
    }:
        return PromotionClass.CREATIVE_LIMITATION
    return PromotionClass.TERMINAL


def _severity(promotion_class: PromotionClass, retryable: bool) -> DefectSeverity:
    if promotion_class is PromotionClass.TECHNICAL_BLOCKER:
        return DefectSeverity.TECHNICAL_BLOCKER
    if promotion_class is PromotionClass.CREATIVE_LIMITATION:
        return DefectSeverity.LIMITATION
    if promotion_class is PromotionClass.ADVISORY:
        return DefectSeverity.ADVISORY
    return DefectSeverity.RETRYABLE if retryable else DefectSeverity.TERMINAL


def _fallback(code: str) -> str | None:
    if code == "PREDICTIVE_SUBTITLE_SAFE_ZONE_CONFLICT":
        return "CAPTION_SAFE_ZONE_FALLBACK"
    if code == "PREDICTIVE_ACTIVE_PICTURE_RISK":
        return "VISUAL_REFRAME_FALLBACK"
    if code.startswith("PREDICTIVE_OVERLAY_"):
        return "RENDER_PREFLIGHT_FALLBACK"
    if code.startswith("VISUAL_"):
        return "VISUAL_REFRAME_FALLBACK"
    if code.startswith("CROP_VISUAL") or code in {"ACTIVE_PICTURE_TOO_SMALL"}:
        return "VISUAL_REFRAME_FALLBACK"
    if code in {
        "COMPOSITION_CROP_TARGET_TOO_WIDE",
        "COMPOSITION_LAYOUT_UNSUPPORTED",
    }:
        return "VISUAL_REFRAME_FALLBACK"
    if code.startswith("CAPTION_") or code.startswith("SUBTITLE_"):
        return "CAPTION_SAFE_ZONE_FALLBACK"
    if code in {
        "EDIT_PLAN_REGION_UNKNOWN",
        "EDIT_PLAN_REGION_OUTSIDE_CLIP",
        "EDIT_PLAN_TRACK_UNKNOWN",
        "EDIT_PLAN_TRACK_OUTSIDE_CLIP",
        "EDIT_PLAN_EVIDENCE_UNKNOWN",
        "REGION_REFERENCE_UNKNOWN",
        "REGION_REFERENCE_OUTSIDE_CLIP",
        "TRACK_REFERENCE_UNKNOWN",
        "TRACK_REFERENCE_OUTSIDE_CLIP",
        "EVIDENCE_REFERENCE_UNKNOWN",
        "FULL_FRAME_FALLBACK_UNAPPROVED",
    }:
        return "VISUAL_REFRAME_FALLBACK"
    if code.startswith(("ASSET_OVERLAY_", "ASSET_VISIBILITY_")):
        return "EXTERNAL_ASSET_OMITTED"
    if code in {
        "EDIT_PLAN_ASSET_BUDGET_EXCEEDED",
        "EDIT_PLAN_GENERATED_ASSET_BUDGET_EXCEEDED",
        "EDIT_PLAN_STOCK_ASSET_BUDGET_EXCEEDED",
        "ASSET_BUDGET_EXCEEDED",
        "REQUESTED_ASSETS_MISSING",
        "UNREQUESTED_ASSETS_USED",
    }:
        return "EXTERNAL_ASSET_OMITTED"
    if "TRANSITION" in code:
        return "TRANSITION_FALLBACK"
    if "CAPABILITY" in code or code == "EDIT_PLAN_OVERLAY_BUDGET_EXCEEDED":
        return "EFFECT_OMITTED"
    if code.startswith("FFMPEGA_") or code == "EFFECT_PLANNING_FAILED":
        return "EFFECT_OMITTED"
    if code in _PLAN_REPAIR_CODES or code in _CONDITIONAL_REPAIR_CODES:
        return "RENDER_PREFLIGHT_FALLBACK"
    return None


def _evidence(strategy: RepairStrategy) -> tuple[str, ...]:
    return {
        RepairStrategy.LLM_VISUAL_REPAIR: ("visual_evidence",),
        RepairStrategy.LLM_PLAN_REPAIR: ("edit_plan", "deterministic_validation"),
        RepairStrategy.CONDITIONAL_LLM_OR_FALLBACK: ("creative_intent", "capabilities"),
        RepairStrategy.DETERMINISTIC_FALLBACK: ("fallback_ledger",),
        RepairStrategy.PROVIDER_RETRY: ("provider_attempt",),
        RepairStrategy.RENDERER_RETRY_OR_FAIL: ("technical_qa",),
        RepairStrategy.ADVISORY: ("qa_finding",),
        RepairStrategy.TERMINAL: (),
    }[strategy]


def _predictive_policy(code: str) -> tuple[str | None, str | None, bool]:
    metadata = _PREDICTIVE_METADATA.get(code)
    if metadata is None:
        return None, None, False
    detector, _evidence_types, threshold, trigger_eligible = metadata
    return detector, threshold, trigger_eligible


def _presentation(
    code: str,
    domain: DefectDomain,
    promotion_class: PromotionClass,
) -> tuple[str, str, str, str]:
    override = _PRESENTATION_OVERRIDES.get(code)
    if override is not None:
        return override
    title_en = {
        PromotionClass.ADVISORY: "Creative review recommended",
        PromotionClass.CREATIVE_LIMITATION: "Creative limitation",
        PromotionClass.TECHNICAL_BLOCKER: "Technical blocker",
        PromotionClass.TERMINAL: "Processing issue",
    }[promotion_class]
    title_es = {
        PromotionClass.ADVISORY: "Revision creativa recomendada",
        PromotionClass.CREATIVE_LIMITATION: "Limitacion creativa",
        PromotionClass.TECHNICAL_BLOCKER: "Bloqueo tecnico",
        PromotionClass.TERMINAL: "Incidencia de procesamiento",
    }[promotion_class]
    domain_en, domain_es = _DOMAIN_LABELS[domain]
    readable = code.replace("_", " ").lower()
    return (
        title_en,
        f"The {domain_en} stage reported {readable}.",
        title_es,
        f"La etapa de {domain_es} registro el codigo {code}.",
    )


def _definition(code: str) -> DefectDefinition:
    strategy = _repair_strategy(code)
    promotion_class = _promotion_class(code, strategy)
    retryable = (
        code in _LEGACY_RETRYABLE_CODES
        or strategy in {
            RepairStrategy.ADVISORY,
            RepairStrategy.LLM_VISUAL_REPAIR,
            RepairStrategy.LLM_PLAN_REPAIR,
            RepairStrategy.CONDITIONAL_LLM_OR_FALLBACK,
            RepairStrategy.DETERMINISTIC_FALLBACK,
            RepairStrategy.PROVIDER_RETRY,
            RepairStrategy.RENDERER_RETRY_OR_FAIL,
        }
        or code.endswith(("_TIMEOUT", "_RATE_LIMITED", "_UNAVAILABLE"))
    )
    domain = _domain(code)
    title_en, description_en, title_es, description_es = _presentation(
        code,
        domain,
        promotion_class,
    )
    detector, threshold, trigger_eligible = _predictive_policy(code)
    evidence_requirements = (
        _PREDICTIVE_METADATA[code][1]
        if code in _PREDICTIVE_METADATA
        else _evidence(strategy)
    )
    return DefectDefinition(
        code=code,
        domain=domain,
        default_severity=_severity(promotion_class, retryable),
        visibility=(
            DefectVisibility.PUBLIC if code in _PUBLIC_CODES else DefectVisibility.AUDIT
        ),
        repair_strategy=strategy,
        repair_phase=_repair_phase(code, strategy),
        evidence_requirements=evidence_requirements,
        safe_fallback_code=_fallback(code),
        retryable=retryable,
        retry_action=(RetryAction.RETRY_DEFECTS if retryable else RetryAction.NONE),
        promotion_class=promotion_class,
        title_en=title_en,
        description_en=description_en,
        title_es=title_es,
        description_es=description_es,
        legacy_aliases=(code.lower(),) if code in _PUBLIC_CODES else (),
        detector=detector,
        threshold=threshold,
        trigger_eligible=trigger_eligible,
    )


def _build_registry(codes: Iterable[str]) -> tuple[dict[str, DefectDefinition], dict[str, str]]:
    registry: dict[str, DefectDefinition] = {}
    aliases: dict[str, str] = {}
    for code in sorted(codes):
        if not _SAFE_CODE.fullmatch(code) or code in registry:
            raise RuntimeError(f"invalid or duplicate defect code: {code}")
        definition = _definition(code)
        registry[code] = definition
        for alias in definition.legacy_aliases:
            key = alias.strip().upper()
            owner = aliases.get(key)
            if owner is not None and owner != code:
                raise RuntimeError(f"duplicate defect alias: {alias}")
            aliases[key] = code
    return registry, aliases


_POLICY_CODES = (
    _TECHNICAL_CODES
    | _ADVISORY_CODES
    | _VISUAL_REPAIR_CODES
    | _PLAN_REPAIR_CODES
    | _CONDITIONAL_REPAIR_CODES
    | _FALLBACK_CODES
    | _POST_RENDER_FALLBACK_CODES
    | _PROVIDER_RETRY_CODES
    | _LEGACY_RETRYABLE_CODES
    | _PUBLIC_CODES
)
_registry, _aliases = _build_registry(_REGISTERED_CODES | _POLICY_CODES)
DEFECT_REGISTRY = MappingProxyType(_registry)
DEFECT_ALIASES = MappingProxyType(_aliases)
DEFECT_REGISTRY_SHA256 = sha256(json.dumps(
    {
        code: asdict(definition)
        for code, definition in sorted(DEFECT_REGISTRY.items())
    },
    ensure_ascii=True,
    sort_keys=True,
    separators=(",", ":"),
).encode("utf-8")).hexdigest()

UNKNOWN_DEFECT = DefectDefinition(
    code="UNKNOWN_DEFECT",
    domain=DefectDomain.UNKNOWN,
    default_severity=DefectSeverity.TERMINAL,
    visibility=DefectVisibility.PUBLIC,
    repair_strategy=RepairStrategy.TERMINAL,
    repair_phase=RepairPhase.NONE,
    evidence_requirements=(),
    safe_fallback_code=None,
    retryable=False,
    retry_action=RetryAction.NONE,
    promotion_class=PromotionClass.TECHNICAL_BLOCKER,
    title_en="Unknown processing issue",
    description_en="An unregistered defect code was reported and failed closed.",
    title_es="Incidencia de procesamiento desconocida",
    description_es="Se registro un codigo no reconocido y el proceso fallo de forma segura.",
    detector=None,
    threshold=None,
    trigger_eligible=False,
)


def normalize_defect_code(code: Any) -> str:
    normalized = str(code or "").strip().upper()[:120]
    if not _SAFE_CODE.fullmatch(normalized):
        return "UNKNOWN_DEFECT"
    return DEFECT_ALIASES.get(normalized, normalized)


def defect_definition(code: Any) -> DefectDefinition:
    return DEFECT_REGISTRY.get(normalize_defect_code(code), UNKNOWN_DEFECT)


def defect_public_metadata(code: Any) -> dict[str, Any]:
    candidate = str(code or "").strip().upper()[:120]
    raw_code = candidate if _SAFE_CODE.fullmatch(candidate) else "UNKNOWN_DEFECT"
    normalized = normalize_defect_code(raw_code)
    definition = DEFECT_REGISTRY.get(normalized, UNKNOWN_DEFECT)
    return {
        "registry_version": DEFECT_REGISTRY_VERSION,
        "registered": definition is not UNKNOWN_DEFECT,
        "raw_code": raw_code,
        "canonical_code": definition.code,
        "domain": definition.domain.value,
        "severity": definition.default_severity.value,
        "repair_strategy": definition.repair_strategy.value,
        "repair_phase": definition.repair_phase.value,
        "retryable": definition.retryable,
        "retry_action": definition.retry_action.value,
        "promotion_class": definition.promotion_class.value,
        "detector": definition.detector,
        "threshold": definition.threshold,
        "trigger_eligible": definition.trigger_eligible,
        "en": {"title": definition.title_en, "description": definition.description_en},
        "es": {"title": definition.title_es, "description": definition.description_es},
    }


def retryable_for_code(code: Any, *, legacy_suffix_compatibility: bool = True) -> bool:
    normalized = normalize_defect_code(code)
    definition = DEFECT_REGISTRY.get(normalized)
    if definition is not None:
        return definition.retryable
    return bool(
        legacy_suffix_compatibility
        and normalized.endswith(("_TIMEOUT", "_RATE_LIMITED", "_UNAVAILABLE"))
    )


def promotion_class_for_code(code: Any) -> PromotionClass:
    return defect_definition(code).promotion_class
